name: Go
on: [push,pull_request]

jobs:
  cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.restore-cache.outputs.cache-hit }}
    steps:
      - name: Cache Go dependencies and binaries
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod bin/
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}

  test:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.14'
        id: go
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: make all
